name: music_transcription
channels:
- defaults
- conda-forge
dependencies:
- aubio=0.4.5=np112py35_2
- keras=2.0.6=py35_0
- librosa=0.5.1=py35_1
- matplotlib=2.0.2=np112py35_0
- numpy=1.12.1=py35_0
- python=3.5.2=0
- scikit-learn=0.18.1=np112py35_1
- theano=0.9.0=py35_0
- pip:
  - python-speech-features==0.5
  - soundfile==0.9.0.post1
